Fix: Change scrollToToday animated to false
Error: 'scrollToIndex should be used in conjunction with getItemLayout'
Solution: Set animated: false instead of animated: true
React Native requires getItemLayout for animated scrolls with variable heights